pelias/model

Document.js
README.md
test/document/address.js
test/run.js

the `address` property is already defined in `pelias/schema` [1] this PR simply exposes getter/setter methods to provide an interface to modify the address data.
[1] https://github.com/pelias/schema/blob/master/mappings/poi.js#L7

add address property to Document model

---

Document.js
test/document/id.js
test/document/latlon.js
test/document/popularity.js
test/document/population.js
util/model.js
util/transform.js

The explicit truthy checks [1] and [2] made it difficult to deal with zero values, @hkrishna did a PR to try to revolve this issue which added a `zeroIsValid` property, this was not applied to the `setChild` method [2] and so in order to resolve https://github.com/pelias/openstreetmap/issues/42 (allowing zero values as valid lat/lon co-ords) I needed to revisit this issue.
In order to simplify the code I removed the `zeroIsValid` flag and fixed the stringify coercion; because javascript [3]
[1] https://github.com/pelias/model/blob/8a311de4678b6946400bbb7ec24b3306326f1a1a/util/model.js#L14
[2] https://github.com/pelias/model/blob/8a311de4678b6946400bbb7ec24b3306326f1a1a/util/model.js#L56
[3] https://github.com/pelias/model/compare/explicit_truthy?expand=1#diff-3fe73be3add3db1626cc2c371bed59 …

remove explicit truthy check

---

Document.js
DocumentMapperStream.js
index.js
package.json
test/DocumentMapperStream.js
test/document/toESDocument.js
test/run.js

This is an addition to the `wof_refactor` branch that adds a `Document.toESDocument` method, and a stream that, given Documents, transforms them by calling `toESDocument`. This consolidates the code to do the same thing in our importers [here](https://github.com/pelias/openstreetmap/blob/master/stream/dbmapper.js#L9), [here](https://github.com/pelias/openaddresses/blob/master/lib/import_pipelines.js#L104), [here](https://github.com/pelias/quattroshapes/blob/master/example/runme.js#L151), [here](https://github.com/pelias/geonames/blob/master/task/import.js#L126) and [here](https://github.com/pelias/whosonfirst/blob/master/src/elasticsearchPipeline.js#L13)
Required for pelias/pelias#234

Add document mapper stream

---

Document.js
test/document/toESDocument.js

strip empty arrays and maps from the es document before sending it downstream
prior to this PR when we send quite large documents to ES, a big chunk of the request body can be empty arrays for the `parent.*` fields or an empty `{}` for `address_parts`.
the downside of having these empty fields is 1. network overhead, 2. they actually get stored in the index despite contain no true 'values' and get returned to API from the cluster.
this has actually been bugging me for some time but I didn't know how best to deal with it, in the end I used `JSON.parse( JSON.stringify( _, replacer ) )` to do the job, its a little more CPU but seemed better than the other approaches I considered (key checks on each insert).
I'm hoping we get a little performance bump out of ES due to the reduced size of …

Strip empty arrays and maps from the es document before sending it downstream

---

Document.js
test/Document.js
test/util/model.js
util/model.js

For pelias/geonames#92, the geonames importer should ignore the `locality` and `localadmin` values coming back from wof-admin-lookup and override with the geonames `name` value.  This PR exposes a method that allows a field to be completely removed from a `Document` instance.

added `clearChild` to model and `clearParent` to Document

---

Document.js
package.json
test/document/toESDocument.js

As part of https://github.com/pelias/api/issues/334, we want to be able to configure which Elasticsearch index documents are sent to as they are created. The model code was hardcoded to use `pelias` as the index name. 
Note: this code uses proxyquire to fake using the pelias-config in the tests, and I think it turned out pretty nicely, so check it out.
Requires https://github.com/pelias/config/pull/30 to be merged and pushed as a new version first (update: that PR has been merged and version 2.1.0 includes those changes)

Configurable index name

---

Document.js
test/run.js
test/util/valid.js
util/valid.js

since that's what it's testing for.  also started tests for `util/valid.js`.

changed function name from `positive` to `nonnegative`

---

Document.js
test/Document.js
test/document/alpha3.js
test/util/model.js
util/model.js

Since cloning a `Document` doesn't work, these are useful for handling WOF records with multiple hierarchies:
- `clearAlpha3()`
- `clearAllParents()`

Added convenience functions

---

Document.js
test/document/toESDocument.js

refactor code for performance & readability
this PR removes the slow JSON serialize/deserialize code. that code converts each object to a string and then back in to an object in order to take advantage of a feature in `JSON.stringify` which removes empty properties.
it turns out this is potentially slow, so I refactored the code to do the same thing using a different method.
benchmarks:
```bash
imported 10000 docs in 1124 ms
average speed: 0.1124 ms
imported 10000 docs in 290 ms
average speed: 0.0290 ms
```
works out to be ~75% faster, multiplied out to 500 million records, this change could save 10+ hrs

feat(refactor): refactor toESDocument() to be more efficient

---

Document.js
test/document/toESDocument.js

- added `bounding_box` conditionally to output (was missing entirely)
- remove `center_point` from output when not set (previous behavior)
- added `population` conditionally to output (was missing entirely)
- added `popularity` conditionally to output (was missing entirely)
- added `polygon` conditionally to output (was missing entirely)

expose missing things from toESDocument

---

.travis.yml

set to `2` so semantic release will run after the node 6 build.

assigned BUILD_LEADER_ID

---

.travis.yml
README.md
package.json

Doing our usual upgrade dance for Node.js versions.
This also cleans up some old TravisCI settings.
Connects https://github.com/pelias/pelias/issues/693
Connects https://github.com/pelias/pelias/issues/612
Connects https://github.com/pelias/pelias/issues/723

Drop Node.js 4, add Node.js 8 and 10

---

bin/units
package.json

The way we were running our unit tests does not catch fatal errors in
the unit test run, even though they return non-zero status codes.
By using a dedicated script to run the tests, with the `pipefail`
option, we can catch them.
Connects https://github.com/pelias/pelias/issues/744

chore(test): Use dedicated test script to catch errors

---

Document.js
test/document/parent.js

For some time, we have [used null values](11bd4f6) to ensure Elasticsearch properly handles the optional abbreviation value in parent records.
As a result, we have been very strict in what we allow for values of the abbreviation field. Currently, the Javascript value `undefined` is converted to `null` (Elasticsearch has `null` but not `undefined`), and passing `null` in is forbidden.
However, this means that if we wish to take a value that has been already added with `addParent` and "re-add" it (perhaps after some processing, as in pelias/wof-admin-lookup#232), the model code will throw a validation error.
This PR changes `addParent` to accept any value with `typeof` `string`. All others are stored as `null`s. After testing of importing around 5 million OSM records from around the world, …

fix(addParent): support any string value for abbreviations, use `null` for all others

---

Document.js
README.md
codec.js
index.js
test/document/addendum.js
test/document/toESDocument.js
test/run.js
test/serialize/test.js

This PR addresses the issue mentioned in pelias/pelias#747, also known as 'custom data'.
This change would allow the operators of a Pelias instance to store arbitrary data alongside any document.
The addendum entries are 'namespaced' and encoded as strings before being saved to elasticsearch.
paired with:
- https://github.com/pelias/schema/pull/342
- https://github.com/pelias/api/pull/1255

allow arbitrary data to be stored alongside the rest of the document

---

Document.js
post/intersections.js
test/document/post.js
test/document/toESDocument.js
test/post/intersections.js
test/run.js

This PR improves support for intersection matching in Pelias.
It introduces a new `layer` called `intersection` as well as a new `address_parts` property called `cross_street`.
I've also added a new concept within the `pelias/model` code which allow registering of "post-processing scripts" which are executed within the `toESDocument` function before being converted to the ES schema format.
The `post/intersections.js` function I've added detects documents from the `intersection` layer and adds additional name aliases as such:
```js
// corner of A & B
doc.setNameAlias('default', `${street} & ${cross_street}`);
doc.setNameAlias('default', `${street} @ ${cross_street}`);
doc.setNameAlias('default', `${street} at ${cross_street}`);
doc.setNameAlias('default', `Corner of ${street} & …
```

support common intersection syntactic variations

---

Document.js
test/document/address.js
test/document/name.js
test/util/valid.js
util/valid.js

We recently discovered some open-data which incorrectly contains URLs in the `name` & `housenumber` fields.
Unfortunately, this seems to be a common problem in openstreetmap due to human error.
This PR enforces a regex check on `name` and `address` fields to ensure that they do not contain URLs.

do not allow urls in name and address fields

---

Document.js
post/deduplication.js
test/document/post.js
test/post/deduplication.js
test/run.js

I was inspecting some raw elasticsearch results today and noticed that there is a lot of duplication in the WOF data for the `name.default` field.
This PR adds deduplication of these arrays using a fancy new `postprocessing` script.
eg.
```
"default": [
"New York",
"New York"
]
"default": [
"New York Mills",
"New York Mills",
"New York Mls"
]
```

add deduplication post processing script

---

package.json
test/DocumentMapperStream.js

Replacing event-stream with stream-mock as discussed in pelias/pelias#801

tests(document-mapper) move away from event-stream

---

Document.js
test/document/toESDocument.js

BREAKING CHANGE: The Pelias GID is now stored in Elasticsearch's `_id` field, in order to remove the potential for two different documents to conflict with the previous mapping.
pelias/api v3.79.0 (d5f4e411) is required to support this change.
This implements step 3 in https://github.com/pelias/pelias/issues/672#issuecomment-508837195
Connects https://github.com/pelias/pelias/issues/672
Connects https://github.com/pelias/pelias/issues/719

Store GID in Elasticsearch _id field

---

Document.js
package.json
test/document/toESDocument.js

this pairs with https://github.com/pelias/config/pull/118
the motivation is being *able to* create indices compatible with ES7 while not yet breaking backwards support for ES5.
this allows us to create ES7 compatible indices using either ES6 or ES7 without breaking backwards compatibility with 5 yet.
the major motivation for this is that users currently building on `pelias/docker` on ES6 are going to find that the indices they created with ES6 (using `_type:doc`) are incompatible with ES7 (and also incompatible with ES6 once we change the type name to `_doc`!)
that doesn't really make sense, so I plan to set the `config.schema.typeName` variable to `_doc` in `pelias/docker` projects so that indices built with ES6 will not incur any breaking changes.
this is much preferred because without …

support for dynamically specifying the elasticsearch _type from config

---

Document.js
README.md
test/benchmark.js
test/document/shape.js
test/document/toESDocument.js
test/run.js
test/serialize/test.js

The setPolygon() and getPolygon() methods are replaced by setShape() & getShape().
This ensures the field and method names are consistent with Pelias Schema.
As discussed in https://github.com/pelias/schema/pull/466 the field name should be `shape`, not `polygon`.
It's astounding that it's gone 3 years without anyone noticing that it didn't actually work, most likely because it's not very often used.

rename 'polygon' field to 'shape' to match pelias/schema

---

Document.js
post/language_field_trimming.js
test/document/post.js
test/post/language_field_trimming.js
test/run.js

This PR adds a new 'post processing' script which aims to delete any names stored in language fields which are duplicated in the `default` language.
From the code comments:
```
/**
* Language field post-processing script ensures that language tokens
* present in the 'default' language are not duplicated in other languages.
*
* By default Pelias searches on the `name.default` field, and in some cases
* it additionally searches on the language of the browser agent.
*
* This means that any name which exists in `name.default` need not additionally
* exist in any of the other language fields.
*
* The benefits of this are that we can reduce the index size and any TF/IDF penalties.
*
* Example: the term 'Berlin' is indexed in *both* `name.default` and `name.de`.
* In this case the `de` copy of …
```

add language_field_trimming post processing script

---

.jshintrc
Document.js
test/serialize/test.js

At the time of this PR, when we build the hierarchy, we use [pelias/pip-service](https://github.com/pelias/pip-service) which is an In Memory Point-In-Polygon lookup service based on WOF data. That means, when we have something in the hierarchy, it's necessarily from WOF.
As a result, in the API, when we retrieve data from PIP Service, the source WOF is [hard-codded](https://github.com/pelias/api/blob/76a31d96d092dc67005a994728941ca739ed3bec/controller/coarse_reverse.js#L70).
The future of PIP is [pelias/spatial](https://github.com/pelias/spatial) which supports a plethora of sources. I start the work for a smooth integration from the beginning.
Since spatial is not yet used, the source will always be `null` and the code is 100% backward compatible. ~~I changed the fourth parameter to an …

Support custom source for parents

---

Document.js
post/popularity.js
test/document/post.js
test/post/popularity.js
test/run.js

As discussed in https://github.com/pelias/openstreetmap/pull/493#issuecomment-503019975, this draft PR ensures that documents on the `postalcode` layer receive a minimum `popularity` value.
I'm opening this up for testing now, I think (if it's successful) that we will probably want to make the `MIN_POPULARITY_MAP` structure configurable via `pelias/config`.
note: I've selected an initial value of `9000` for testing postalcodes, this is just a guess based on the values in https://github.com/pelias/openstreetmap/blob/master/stream/popularity_mapper.js and may need to be refined, pending testing.

popularity bands

---

post/language_field_trimming.js
test/post/language_field_trimming.js

I found a bug introduced in https://github.com/pelias/model/pull/135.
The test fixtures in https://github.com/pelias/openstreetmap/pull/554 *shouldn't* have changed but they did.
It turns out there was a bug in https://github.com/pelias/model/pull/135 which wasn't handling scalar vs. array type names correctly.
This PR resolved the issue.

bugfix for https://github.com/pelias/model/pull/135

---

.github/workflows/push.yml
package.json

This copies the Github Actions workflow from the Pelias API project.
It brings in a few notable changes:
- Run all tests against Node.js 12, 14, and 16
- Remove MacOS build jobs (they're 10x the cost, which could hurt anyone running these on private forks)
- Update jobs to run on Ubuntu 20 (Ubuntu 16 is deprecated: https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/)
- Run docker build _after_ any NPM publish, so that versioned docker images can be built
- Remove any CircleCI config that exists (we can use Github Actions to build docker images just fine)
- Remove any lingering references to TravisCI

Update GitHub actions

---

post/_contractions_abbreviated.json
post/seperable_street_names.js
test/post/seperable_street_names.js

implementation of https://github.com/pelias/model/issues/144
this method is slightly different from previous in that *all* versions of the name (including aliases) are considered rather than only the primary name.
note: this method produces duplicate names, the subsequent post processing step 'deduplication' handles removing duplicate entries so I felt it wasn't necessary to do so within this script, at the cost of having duplicate entries in the tests.
resolves https://github.com/pelias/model/issues/144
resolves https://github.com/pelias/api/issues/1594

add alias for compound street names with abbreviated generic

---

Document.js
test/Document.js

:wave: 
---
I need to update the [pelias-csv-importer](https://github.com/pelias/csv-importer) to support the import of parent field. And found that the addParent function does not validate the field name with the list of parentFields, like it is done with the addressFields in setAddress function.
---
Updated the addParent to function by adding the property validation for parentFields.
Added the unit test to test the change.

Adding parentFields validation in addParent.

---

Document.js
package.json
test/document/toESDocument.js

now that elasticsearch v6 support has been dropped we can remove any references to `_type` from this repo.
related: https://github.com/pelias/dbclient/pull/128
note: this should be versioned as a BREAKING CHANGE

remove _type

---

Document.js
post/alphanumeric_postcodes.js
test/document/post.js
test/post/alphanumeric_postcodes.js
test/run.js

```
/**
* Alphanumeric postcodes post-processing script ensures that both the expanded
* and contracted version of alphanumeric postcodes are indexed.
*
* Without this script a postcode such as '1383GN' would not be matched to the
* query '1383'.
* 
* The script is intended to detect these alphanumeric postcodes and index both
* permutations, ie. '1383GN' = ['1383GN', '1383 GN'].
* 
* The inverse case should also be covered. ie. '1383 GN' = ['1383 GN', '1383GN'].
* 
* Note: the regex is currently restrictive by design, the UK for instance uses
* alphanumeric postcodes in the format 'E81DN' which could cause error when splitting
* with this method, they are currently ignored. Future work should consider global
* postcode formats.
* 
* Note: this script is intended to run *before* the …
```

add alphanumeric postcodes post-processing script

---

.github/workflows/_test.yml
.github/workflows/push.yml

This PR includes a bunch of commits made by a script that standardizes as much as possible our CI config across all repositories.
First and foremost, it ensures we test all Node.js versions that are an LTS release, not EOL, and currently work with this repository.
Also, the CI OS version is now hardcoded to ubuntu-22.04. We fooled around with an organization wide CI variable to configure that, but it broke CI in forks and doesn't really help us much, so it's now undone.
If there are any other differences in Github Actions Workflow files, they are also now removed by using a standard template.
Connects https://github.com/pelias/pelias/issues/950
Connects https://github.com/pelias/pelias/issues/951

CI updates: Modern Node.js versions, action version updates, standard template

---

Document.js
test/document/address.js
test/document/name.js
util/transform.js

as suggested in https://github.com/pelias/polylines/pull/280#issuecomment-2533733793 this PR strips URLs from name/address strings *within* the Model module itself.
Discuss!
related https://github.com/pelias/model/pull/115

strip URLs from name/address

---

Document.js
post/zero_prefixed_house_numbers.js
test/document/post.js
test/post/zero_prefixed_house_numbers.js
test/run.js

as discussed in https://github.com/pelias/schema/issues/503

add zero_prefixed_house_numbers script

---

post/zero_prefixed_house_numbers.js
test/post/zero_prefixed_house_numbers.js

following on from https://github.com/pelias/model/pull/162 this PR addresses some issues and omissions I discovered when updating the importers:
1. A house number of many zero (such as `00000`) would return an empty string and error, this actually occurs in live data, we now squash it to `0`.
2. The 'name' field(s) were not being updated. I thought through a few different options including updating all the importers directly and settled on this code which handles it fairly elegantly.

zero prefixed house numbers
